/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_accept[99] =
    {   0,
        0,    0,    0,    0,   56,   54,    1,    7,   41,    6,
        2,   40,   30,   50,   51,   38,   36,   45,   37,   39,
       19,   19,   46,   47,   43,   42,   44,   29,   16,   52,
       53,   31,   33,   16,   16,   16,   16,   48,   32,   49,
       34,    4,    3,    3,    1,   24,   21,   10,    9,   20,
       19,    0,   20,    0,    0,   27,   25,   23,   26,   28,
       16,   16,   16,    5,   16,   16,   22,    3,    0,    0,
       20,    0,   20,   18,   17,   16,   16,   16,   16,   16,
        0,   16,   16,   13,   16,   16,    0,   11,    0,   16,
       12,    0,   15,    0,    0,   14,    8,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   27,   27,   28,   29,
       30,   31,   31,   31,   31,   31,   32,   31,   31,   33,
       31,   34,   31,   31,   31,   31,   31,   31,   31,   31,
       35,    1,   36,   37,   38,    1,   27,   39,   27,   27,

       40,   41,   31,   31,   42,   31,   31,   31,   31,   43,
       31,   31,   31,   31,   44,   45,   46,   31,   31,   47,
       31,   31,   48,   49,   50,   51,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    3,
        3,    3,    3,    3,    1,    1,    1,    3,    2,    2,
        2,    3,    3,    3,    3,    3,    3,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[101] =
    {   0,
        0,    0,   47,   50,  188,  189,  185,  189,  163,  189,
      189,  189,  177,  189,  189,  189,  189,  189,  189,   42,
       55,   15,  189,  189,   34,  161,   36,  189,    0,  189,
      189,  189,  189,  141,  140,  138,   34,  189,  131,  189,
      189,  189,   60,   24,  177,  189,  189,  189,   59,   69,
        0,   86,  189,   63,    0,  189,  189,  189,  189,  189,
        0,  133,  130,  131,  133,  131,  189,    0,   80,  139,
       89,   72,   97,   94,    0,  111,  102,  105,   81,   82,
       99,  114,  122,  117,  125,  128,   71,  131,  134,  139,
      142,   67,  145,  148,   67,  151,  189,  189,  169,   83

    } ;

static yyconst short int yy_def[101] =
    {   0,
       98,    1,    1,    1,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   21,   98,   98,   98,   98,   98,   98,   99,   98,
       98,   98,   98,   99,   99,   99,   99,   98,   98,   98,
       98,   98,   21,   43,   98,   98,   98,   98,   98,   98,
       22,   98,   98,   98,  100,   98,   98,   98,   98,   98,
       99,   99,   99,   99,   99,   99,   98,   44,   98,   98,
       98,   98,   98,   98,  100,   99,   99,   99,   99,   99,
       98,   99,   99,   99,   99,   99,   98,   99,   98,   99,
       99,   98,   98,   98,   98,   98,   98,    0,   98,   98

    } ;

static yyconst short int yy_nxt[241] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,    6,   20,   21,   22,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   30,   31,   32,   33,   34,   29,
       35,   36,   29,   29,   29,   37,   29,   38,   39,   40,
       41,   42,   48,   98,   42,   56,   57,   49,   59,   60,
       69,   98,   98,   43,   44,   44,   43,   44,   44,   50,
       98,   51,   51,   51,   65,   66,   68,   68,   68,   74,
       74,   69,   52,   53,   75,   71,   71,   71,   73,   73,
       73,   70,   97,   54,   52,   53,   52,   53,   95,   72,

       92,   55,   73,   73,   73,   71,   71,   71,   52,   53,
       74,   74,   70,   73,   73,   73,   52,   53,   83,   83,
       83,   84,   84,   84,   87,   53,   86,   85,   52,   53,
       88,   88,   88,   84,   84,   84,   89,   53,   83,   83,
       83,   90,   90,   90,   91,   91,   91,   88,   88,   88,
       93,   93,   93,   94,   82,   90,   90,   90,   91,   91,
       91,   93,   93,   93,   96,   96,   96,   96,   96,   96,
       61,   61,   81,   80,   79,   78,   77,   76,   45,   67,
       64,   63,   62,   58,   47,   46,   45,   98,    5,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98
    } ;

static yyconst short int yy_chk[241] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,   20,   22,    4,   25,   25,   20,   27,   27,
       49,   22,   44,    3,    3,    3,    4,    4,    4,   21,
       44,   21,   21,   21,   37,   37,   43,   43,   43,   54,
       54,   69,   21,   21,  100,   50,   50,   50,   72,   72,
       72,   49,   95,   21,   21,   21,   50,   50,   92,   52,

       87,   21,   52,   52,   52,   71,   71,   71,   50,   50,
       74,   74,   69,   73,   73,   73,   71,   71,   77,   77,
       77,   78,   78,   78,   81,   73,   80,   79,   71,   71,
       82,   82,   82,   84,   84,   84,   83,   73,   83,   83,
       83,   85,   85,   85,   86,   86,   86,   88,   88,   88,
       89,   89,   89,   90,   76,   90,   90,   90,   91,   91,
       91,   93,   93,   93,   94,   94,   94,   96,   96,   96,
       99,   99,   70,   66,   65,   64,   63,   62,   45,   39,
       36,   35,   34,   26,   13,    9,    7,    5,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,

       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,   98,   98,   98
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#define INITIAL 0
#line 2 "scan.l"
#include "sassy.h"
#include "node.h"
#include "deftab.h"
#include "error.h"
#include "gram.tab.h"

#define STRSIZE 1000

/*
#define PRINTF(x,y) printf (x, y)
*/
#define PRINTF(x,y)

int mylineno = 1;
char scan_str[STRSIZE];
char filename[1024];
char *funcname = NULL;

/* WARNING! Make sure this list of strings has a one-to-one
 * association with the 'keytokens' data structure that follows
 * it!
 */
char *keystrings[] =
    {
    "float",
    "double",
    "complex",
    "dot",
    "cross",
    "real",
    "imag",
    "step",
    "at",
    "array",
    "vector",
    "matrix",
    "cube",
    "sum",
    "min",
    "max",
    "and",
    "or",
    "median",
    "concat",
    "tile",
    "extents",
    "if",
    "else",
    "elif",
    "for",
    "while",
    "switch",
    "case",
    "default",
    "bool",
    "true",
    "false",
    "assert",
    "print",
    "array_conperim",
    "array_sum",
    "array_min",
    "array_max",
    "array_and",
    "array_or",
    "array_median",
    "window",
    "next",
    "product",
    "array_max_indices",
    "array_min_indices",
    "array_product",
    "mean",
    "mode",
    "array_mean",
    "array_mode", 
    "array_histogram",
    "array_concat",
    "histogram",
    "accum",
    "array_accum",
    "st_dev",
    "array_st_dev",
    "return",
    "final",
    "loop_indices",
    "vals_at_first_min",
    "vals_at_first_max",
    "vals_at_last_min",
    "vals_at_last_max",
    "vals_at_mins",
    "vals_at_maxs",
    "export",
    "no_inline",
    "no_unroll",
    "no_dfg",
    "lookup",
    "stripmine",
    "no_fuse",
    "block",
    "vhdl"
    };

int keytokens[] =
    {
    TOK_FLOAT,
    TOK_DOUBLE,
    TOK_COMPLEX,
    TOK_DOT,
    TOK_CROSS,
    TOK_REAL,
    TOK_IMAG,
    TOK_STEP,
    TOK_AT,
    TOK_ARRAY,
    TOK_VECTOR,
    TOK_MATRIX,
    TOK_CUBE,
    TOK_SUM,
    TOK_MIN,
    TOK_MAX,
    TOK_RED_AND,
    TOK_RED_OR,
    TOK_MEDIAN,
    TOK_CONCAT,
    TOK_TILE,
    TOK_EXTENTS,
    TOK_IF,
    TOK_ELSE,
    TOK_ELIF,
    TOK_FOR,
    TOK_WHILE,
    TOK_SWITCH,
    TOK_CASE,
    TOK_DEFAULT,
    TOK_BOOL,
    TOK_TRUE,
    TOK_FALSE,
    TOK_ASSERT,
    TOK_PRINT,
    TOK_ARR_CONPERIM,
    TOK_ARR_SUM,
    TOK_ARR_MIN,
    TOK_ARR_MAX,
    TOK_ARR_RED_AND,
    TOK_ARR_RED_OR,
    TOK_ARR_MEDIAN,
    TOK_WINDOW,
    TOK_NEXT,
    TOK_PRODUCT,
    TOK_ARR_MAX_INDICES,
    TOK_ARR_MIN_INDICES,
    TOK_ARR_PRODUCT,
    TOK_MEAN,
    TOK_MODE,
    TOK_ARR_MEAN,
    TOK_ARR_MODE,
    TOK_ARR_HIST,
    TOK_ARR_CONCAT,
    TOK_HIST,
    TOK_ACCUM,
    TOK_ARR_ACCUM,
    TOK_ST_DEV,
    TOK_ARR_ST_DEV,
    TOK_RETURN,
    TOK_FINAL,
    TOK_LOOP_INDICES,
    TOK_VAL_AT_FIRST_MIN,
    TOK_VAL_AT_FIRST_MAX,
    TOK_VAL_AT_LAST_MIN,
    TOK_VAL_AT_LAST_MAX,
    TOK_VAL_AT_MINS,
    TOK_VAL_AT_MAXS,
    TOK_EXPORT,
    TOK_NO_INLINE,
    TOK_NO_UNROLL,
    TOK_NO_DFG,
    TOK_LOOKUP,
    TOK_STRIPMINE,
    TOK_NO_FUSE,
    TOK_BLOCK,
    TOK_VHDL
    };

char *intrinsics[] = {
    "sin",
    "cos",
    "tan",
    "asin",
    "acos",
    "atan",
    "atan2",
    "sinh",
    "cosh",
    "tanh",
    "asinh",
    "acosh",
    "atanh",
    "sqrt",
    "cbrt",
    "pow",
    "modf",
    "exp",
    "frexp",
    "ldexp",
    "log",
    "log10",
    "expm1",
    "log1p",
    "ceil",
    "fabs",
    "floor",
    "fmod",
    "copysign",
    "hypot",
    "rint"
    };

Intrinsic iref[] = {
    IntrinSin,
    IntrinCos,
    IntrinTan,
    IntrinAsin,
    IntrinAcos,
    IntrinAtan,
    IntrinAtan2,
    IntrinSinh,
    IntrinCosh,
    IntrinTanh,
    IntrinAsinh,
    IntrinAcosh,
    IntrinAtanh,
    IntrinSqrt,
    IntrinCbrt,
    IntrinPow,
    IntrinModf,
    IntrinExp,
    IntrinFrexp,
    IntrinLdexp,
    IntrinLog,
    IntrinLog10,
    IntrinExpm1,
    IntrinLog1p,
    IntrinCeil,
    IntrinFabs,
    IntrinFloor,
    IntrinFmod,
    IntrinCopysign,
    IntrinHypot,
    IntrinRint
    };

#define PREPROC 1

#line 712 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 270 "scan.l"

#line 865 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 99 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 189 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 271 "scan.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 272 "scan.l"
{
			/* assume that this is a line number from 'cpp' */
			BEGIN(PREPROC);
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 276 "scan.l"
{
			sscanf (yytext, "%d", &mylineno);
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 279 "scan.l"
{
			int idx = 0;
			int ch;

			/* grab the file name */
			while ((idx < STRSIZE) && (ch = input ()))
			    switch (ch)
				{
				case '\"' :
				    scan_str[idx] = '\0';
				    goto StrEnd;
				case '\n' :
				    mylineno++;
				    handle_error (ErrScanDanglingString, Deadly,
				    		mylineno, filename, funcname);
				default :
				    scan_str[idx] = ch;
				    idx++;
				    break;
				}
			StrEnd:
			strcpy (filename, scan_str);

			/* now chew up the rest of the line and reset to INITIAL state */
			while (input () != '\n');

			BEGIN(INITIAL);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 307 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return TOK_GEN;
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 311 "scan.l"
{
			int idx = 0;
			int ch;

			while ((idx < STRSIZE) && (ch = input ()))
			    switch (ch)
				{
				case '\"' :
				    scan_str[idx] = '\0';
				    goto StrEnd1;
				case '\n' :
				    mylineno++;
				    handle_error (ErrScanDanglingString, Deadly,
				    		mylineno, filename, funcname);
				default :
				    scan_str[idx] = ch;
				    idx++;
				    break;
				}
			StrEnd1:
			yylval = make_node (STRING, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			SacMalloc (yylval->Strval, char*, (idx+1) * sizeof (char))
			strcpy (yylval->Strval, scan_str);
			PRINTF ("%s\n", yytext);
			return TOK_STRING; 
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 339 "scan.l"
{
			mylineno++;
			}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 342 "scan.l"
{
			return TOK_PRAGMA;
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 345 "scan.l"
{
			while (input () != '\n');
			mylineno++;
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 349 "scan.l"
{
			int state;
			int ch;

			state = 0;
			while (state < 2)
			    {
			    ch = input ();
			    if (ch == '\n')
				mylineno++;
			    switch (ch)
				{
				case '*' :
				    state = 1;
				    break;
				case '/' :
				    if (state == 1)
				      state = 2;
				    break;
				case EOF :
				    handle_error (ErrScanDanglingComment,
				    		Deadly, mylineno, filename, funcname);
				default	:
				    state = 0;
				}
			    }
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 376 "scan.l"
{
			int sz;
			yylval = make_node (BITSTYPE, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			sscanf (yytext+4, "%d", &sz);
			yylval->Totsize = sz;
			if (sz > 32)
			    handle_error (ErrScanBitWidth,
			    		Deadly, mylineno, filename, funcname);
			if (sz < 1)
			    handle_error (ErrScanBitWidthLow,
			    		Deadly, mylineno, filename, funcname);
			PRINTF ("%s\n", yytext);
			return TOK_BITS;
			}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 392 "scan.l"
{
			int sz;
			yylval = make_node (UINTTYPE, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			sscanf (yytext+4, "%d", &sz);
			yylval->Totsize = sz;
			if (sz > 32)
			    handle_error (ErrScanBitWidth,
			    		Deadly, mylineno, filename, funcname);
			if (sz < 1)
			    handle_error (ErrScanBitWidthLow,
			    		Deadly, mylineno, filename, funcname);
			PRINTF ("%s\n", yytext);
			return TOK_INT;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 408 "scan.l"
{
			int sz;
			yylval = make_node (INTTYPE, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			sscanf (yytext+3, "%d", &sz);
			yylval->Totsize = sz;
			if (sz > 32)
			    handle_error (ErrScanBitWidth,
			    		Deadly, mylineno, filename, funcname);
			if (sz < 2)
			    handle_error (ErrScanBitWidthLow,
			    		Deadly, mylineno, filename, funcname);
			PRINTF ("%s\n", yytext);
			return TOK_INT;
			}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 424 "scan.l"
{
			int tsz, fsz;
			char *c;
			yylval = make_node (UFIXTYPE, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			sscanf (yytext+4, "%d", &tsz);
			yylval->Totsize = tsz;
			if (tsz > 32)
			    handle_error (ErrScanBitWidth,
			    		Deadly, mylineno, filename, funcname);
			if (tsz < 1)
			    handle_error (ErrScanBitWidthLow,
			    		Deadly, mylineno, filename, funcname);
			for (c=yytext; (*c)!='.'; c++);
			sscanf (c+1, "%d", &fsz);
			yylval->Fracsize = fsz;
			if (fsz > tsz)
			    handle_error (ErrScanBitWidthFrac,
			    		Deadly, mylineno, filename, funcname);
			PRINTF ("%s\n", yytext);
			return TOK_FIX;
			}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 447 "scan.l"
{
			int tsz, fsz;
			char *c;
			yylval = make_node (FIXTYPE, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			sscanf (yytext+3, "%d", &tsz);
			yylval->Totsize = tsz;
			if (tsz > 32)
			    handle_error (ErrScanBitWidth,
			    		Deadly, mylineno, filename, funcname);
			if (tsz < 2)
			    handle_error (ErrScanBitWidthLow,
			    		Deadly, mylineno, filename, funcname);
			for (c=yytext; (*c)!='.'; c++);
			sscanf (c+1, "%d", &fsz);
			yylval->Fracsize = fsz;
			if (fsz >= tsz)
			    handle_error (ErrScanBitWidthFrac,
			    		Deadly, mylineno, filename, funcname);
			PRINTF ("%s\n", yytext);
			return TOK_FIX;
			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 470 "scan.l"
{
			int n, i;
			SYM_ENTRY *s;

			n = sizeof (keystrings) / sizeof (char*);

			for (i=0; i<n; i++)
			    if (strcmp (keystrings[i], yytext) == 0)
				{
				PRINTF ("%s\n", yytext);
				return (keytokens[i]);
				}

			n = sizeof (intrinsics) / sizeof (char*);

			for (i=0; i<n; i++)
			    if (strcmp (intrinsics[i], yytext) == 0)
				{
				PRINTF ("%s\n", yytext);
				yylval = make_node (INTRINSIC_FUNC, NULL, NULL,
					NULL, NULL, NULL, NULL, mylineno,
					handle_filename (filename), funcname);
				yylval->Intrinval = iref[i];
				return (TOK_INTRINSIC);
				}

			s = handle_ident (yytext);
			yylval = make_node (IDENT, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			yylval->Symval = s->val;
			yylval->Defval = -1;
			PRINTF ("%s\n", yytext);
			return (TOK_IDENT);
			}
	YY_BREAK
case 17:
#line 506 "scan.l"
case 18:
#line 507 "scan.l"
case 19:
YY_RULE_SETUP
#line 507 "scan.l"
{
			char *str;
			yylval = make_node (INTNUM, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			SacMalloc (str, char*, 1 + strlen (yytext))
			strcpy (str, yytext);
			yylval->Strval = str;
			PRINTF ("%s\n", yytext);
			return (TOK_INTNUM);
			}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 518 "scan.l"
{
			char *str;
			yylval = make_node (FLOATNUM, NULL, NULL, NULL,
				NULL, NULL, NULL, mylineno,
				handle_filename (filename), funcname);
			SacMalloc (str, char*, 1 + strlen (yytext))
			strcpy (str, yytext);
			yylval->Strval = str;
			PRINTF ("%s\n", yytext);
			return (TOK_FLOATNUM);
			}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 529 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_AND);
			}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 533 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_OR);
			}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 537 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_EQUAL);
			}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 541 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_NE);
			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 545 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_LE);
			}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 549 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (TOK_GE);
			}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 553 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return TOK_LEFT_SHIFT;
			}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 557 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return TOK_RIGHT_SHIFT;
			}
	YY_BREAK
case 29:
#line 562 "scan.l"
case 30:
#line 563 "scan.l"
case 31:
#line 564 "scan.l"
case 32:
#line 565 "scan.l"
case 33:
#line 566 "scan.l"
case 34:
#line 567 "scan.l"
case 35:
#line 568 "scan.l"
case 36:
#line 569 "scan.l"
case 37:
#line 570 "scan.l"
case 38:
#line 571 "scan.l"
case 39:
#line 572 "scan.l"
case 40:
#line 573 "scan.l"
case 41:
#line 574 "scan.l"
case 42:
#line 575 "scan.l"
case 43:
#line 576 "scan.l"
case 44:
#line 577 "scan.l"
case 45:
#line 578 "scan.l"
case 46:
#line 579 "scan.l"
case 47:
#line 580 "scan.l"
case 48:
#line 581 "scan.l"
case 49:
#line 582 "scan.l"
case 50:
#line 583 "scan.l"
case 51:
#line 584 "scan.l"
case 52:
#line 585 "scan.l"
case 53:
YY_RULE_SETUP
#line 585 "scan.l"
{
			PRINTF ("%s\n", yytext);
			return (yytext[0]);
			}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 589 "scan.l"
{
			handle_error (ErrScanInvalidChar, Fatal,
				mylineno, filename, funcname, (int)(yytext[0]));
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 593 "scan.l"
ECHO;
	YY_BREAK
#line 1413 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PREPROC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 99 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 99 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 98);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 593 "scan.l"

int yywrap()
    {
    fclose (yyin);
    return (1);
    }
